public enum PACKET_TYPES
{
    ID_ASSIGNMENT = 0,
    TURN_DATA = 1,
    TURN_INFO = 2,
    PICK_UP_CARD_REQUEST = 3,
    PICK_UP_CARD_ANSWER = 4,
    END_TURN_REQUEST = 5,
    NEW_PLAYER = 6,
    START_GAME = 7,
    CLIENT_READY = 8,
    CURSOR_UPDATE = 9,
    SHOP_SCENE_CHANGE = 10,
    PLAY_ABLITIY = 11,
    DECK_SWAP = 12,
    FOLD = 13,
    SETUP_PLACE = 14,
}